version: "3.4"

services:
  api_123milhas_prod:
    image: api_123milhas_prod:latest
    container_name: api_123milhas_container_prod
    build:
      context: .
      dockerfile: ./.docker/build.Dockerfile